baseURL = "localhost:1313/"
languageCode = "en-us"
title = "Don't Be Me Podcast"
subtitle = "A Comedic Biographical Serious Podcast"
description = "This podcast is about my life, what I have learned and what I would have done different. My target audience is anyone who wants to listen but is mainly aimed at my kids. By doing this podcast they can one day hear me talk about the things I could not when they were young."
theme = "dontbeme"
relativeURLs = true
disableKinds = ["section","taxonomy","taxonomyTerm","RSS","404","sitemap"]
language = "en-us"
email = "paul@dontbemepodcast.com"
podcastImageURL = "img/ituneslogo.png"
atomLink = "https://dontbemepodcast.com/rss.xml"
itunesAuthor = "paul@dontbemepodcast.com"
itunesSummary = '<![CDATA[link <a href="http://example.com">example.com</a>]]>'
itunesImage = "url to image"
itunesExplicit = "yes"